name: tune
#on:
 # schedule:
      - cron: '0 1 * * *'
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-python@v2
#        with:
#          python-version: '3.8.12'
#      - run: pip install -r requirements.txt
#      - run: python3 model_tuning.py
#      - run: |
#          git config user.name github-actions
#          git config user.email github-actions@github.com
#          git add .
#          git commit -m "generated"
#          git push
